services:
  php:
    build:
      context: .
      dockerfile: DockerFile
    container_name: php_app
    ports:
      - "8888:80" # Expondo a porta 8080 do host para o Apache no container
    volumes:
      - ./public:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Script para inicializar o banco de dados:w
    container_name: mysql_db
    ulimits:
      nproc: 65535
      nofile:
        soft: 26677
        hard: 46677
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: tecnofit
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    

volumes:
  dbdata: